# Generated by Django 2.0.1 on 2019-08-26 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userentity',
            options={'verbose_name': '客户管理', 'verbose_name_plural': '客户管理'},
        ),
        migrations.AlterField(
            model_name='userentity',
            name='age',
            field=models.IntegerField(default=0, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='name',
            field=models.CharField(max_length=20, verbose_name='账号'),
        ),
        migrations.AlterField(
            model_name='userentity',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号'),
        ),
    ]
