# Generated by Django 2.0.1 on 2019-08-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_fruitcartentity'),
    ]

    operations = [
        migrations.AddField(
            model_name='fruitentity',
            name='users',
            field=models.ManyToManyField(db_column='user_id', db_table='user_collect_fruits', related_name='users', to='mainapp.UserEntity'),
        ),
    ]
