# Generated by Django 2.0.1 on 2019-08-30 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20190829_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='userentity',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='口令'),
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fruits', to='mainapp.CateTypeEntity'),
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='tags',
            field=models.ManyToManyField(blank=True, db_table='t_fruit_tags', related_name='fruits', to='mainapp.TagEntity', verbose_name='所有标签'),
        ),
        migrations.AlterField(
            model_name='fruitentity',
            name='users',
            field=models.ManyToManyField(blank=True, db_table='t_collect', related_name='fruits', to='mainapp.UserEntity', verbose_name='收藏用户列表'),
        ),
    ]
