# Generated by Django 2.0.1 on 2019-08-29 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_fruitentity_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fruitentity',
            name='users',
            field=models.ManyToManyField(db_column='user_id', db_table='user_collect_fruits', related_name='users', related_query_name='user_id', to='mainapp.UserEntity'),
        ),
    ]
