# Generated by Django 2.0.1 on 2019-08-29 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_auto_20190829_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fruitentity',
            name='users',
        ),
    ]
